language: php

sudo: false

cache:
    - $HOME/.composer/cache/files

os:
  - linux

php:
    - 5.6
    - 7.0
    - 7.1

before_install:
    - 'echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'
    - 'echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'

install:
    - travis_retry composer require satooshi/php-coveralls '~1.0'
    - travis_retry composer install --no-interaction --prefer-dist

before_script:
    - mkdir -p build/coverage
    - mkdir -p build/logs
    - php bin/console doctrine:database:create -e test
    - php bin/console doctrine:schema:create -e test

script:
    - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
    - travis_retry php vendor/bin/coveralls -v
    - wget https://scrutinizer-ci.com/ocular.phar
    - travis_retry  php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
    - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    -  guillaume.caouissin@gmail.com