language: php

sudo: false

cache:
    - $HOME/.composer/cache/files

os:
  - linux

php:
    - 5.6
    - 7.0
    - 7.1

before_install:
  - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer self-update
    - travis_retry composer require satooshi/php-coveralls:1.0.0
    - travis_retry composer install --no-interaction --prefer-dist

before_script:
    - mkdir -p build/coverage
    - mkdir -p build/logs

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - travis_retry php vendor/bin/coveralls -v
  - travis_retry  php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    -  guillaume.caouissin@gmail.com