language: php

sudo: false

cache:
    - $HOME/.composer/cache/files

os:
  - linux

php:
    - 7.0
    - 7.1

before_install:
    - 'echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'
    - 'echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'

install:
    - travis_retry composer require satooshi/php-coveralls '~1.0'
    - travis_retry composer install --no-interaction --prefer-dist

before_script:
    - mkdir -p build/coverage
    - mkdir -p build/logs
    - php bin/console doctrine:database:create -e test
    - php bin/console doctrine:schema:create -e test

script:
    - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
    - travis_retry php vendor/bin/coveralls -v

notifications:
  email:
    -  guillaume.caouissin@gmail.com