services:
    starkerxp_utilisateur.manager.utilisateur:
        class: Starkerxp\UtilisateurBundle\Manager\UtilisateurManager
        arguments: ["@doctrine.orm.entity_manager", "Starkerxp\\UtilisateurBundle\\Entity\\Utilisateur", "@security.password_encoder"]
        tags:
            - { name: starkerxp.manager.entity }
