starkerxp_user.user.cget:
    path: /users
    defaults:
        _controller: 'StarkerxpUserBundle:User:cget'
    methods:
        - GET
starkerxp_user.user.get:
    path: '/users/{user_id}'
    defaults:
        _controller: 'StarkerxpUserBundle:User:get'
    methods:
        - GET
    requirements:
        user_id: \d+
starkerxp_user.user.post:
    path: /users
    defaults:
        _controller: 'StarkerxpUserBundle:User:post'
    methods:
        - POST
starkerxp_user.user.put:
    path: '/users/{user_id}'
    defaults:
        _controller: 'StarkerxpUserBundle:User:put'
    methods:
        - PUT
    requirements:
        user_id: \d+
starkerxp_user.user.delete:
    path: '/users/{user_id}'
    defaults:
        _controller: 'StarkerxpUserBundle:User:delete'
    methods:
        - DELETE
    requirements:
        user_id: \d+
