services:
    starkerxp_campagne.manager.campagne:
        class: Starkerxp\CampagneBundle\Manager\CampagneManager
        arguments: ["@doctrine.orm.entity_manager", "Starkerxp\\CampagneBundle\\Entity\\Campagne"]

    starkerxp_campagne.manager.render:
            class: Starkerxp\CampagneBundle\Render\RenderManager
