services:
    starkerxp_campagne.manager.render:
        class: Starkerxp\CampagneBundle\Render\RenderManager

    starkerxp_campagne.manager.campagne:
        class: Starkerxp\CampagneBundle\Manager\CampagneManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - Starkerxp\CampagneBundle\Entity\Campagne
        tags:
            - { name: starkerxp.manager.entity }

    starkerxp_campagne.manager.template:
        class: Starkerxp\CampagneBundle\Manager\TemplateManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - Starkerxp\CampagneBundle\Entity\Template
        tags:
            - { name: starkerxp.manager.entity }

