services:
#    starkerxp_campagne.example:
#        class: Starkerxp\CampagneBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    starkerxp_campagne.manager.campagne:
        class: Starkerxp\CampagneBundle\Manager\CampagneManager
        arguments: ["@doctrine.orm.entity_manager", "Starkerxp\\CampagneBundle\\Entity\\Campagne"]

    starkerxp_campagne.manager.module_template:
        class: Starkerxp\CampagneBundle\Manager\ModuleTemplateManager
        arguments: ["@doctrine.orm.entity_manager", "Starkerxp\\CampagneBundle\\Entity\\ModuleTemplate"]

    starkerxp_campagne.manager.render:
            class: Starkerxp\CampagneBundle\Services\Render\RenderManager
