services:
#    starkerxp_campagne.example:
#        class: Starkerxp\CampagneBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    starkerxp_campagne.render.buzzexpert:
        class: Starkerxp\CampagneBundle\Services\Render\BuzzExpertRender
    starkerxp_campagne.render.twig:
        class: Starkerxp\CampagneBundle\Services\Render\TwigRender
        arguments: ["@twig"]
    starkerxp_campagne.render.octosend_html:
        class: Starkerxp\CampagneBundle\Services\Render\OctosendHtmlRender
    starkerxp_campagne.render.octosend_txt:
        class: Starkerxp\CampagneBundle\Services\Render\OctosendTxtRender
