starkerxp_campagne.template.cget:
    path: /templates
    defaults:
        _controller: 'StarkerxpCampagneBundle:Template:cget'
    methods:
        - GET
starkerxp_campagne.template.get:
    path: '/templates/{template_id}'
    defaults:
        _controller: 'StarkerxpCampagneBundle:Template:get'
    methods:
        - GET
    requirements:
        template_id: \d+
starkerxp_campagne.template.post:
    path: /templates
    defaults:
        _controller: 'StarkerxpCampagneBundle:Template:post'
    methods:
        - POST
starkerxp_campagne.template.put:
    path: '/templates/{template_id}'
    defaults:
        _controller: 'StarkerxpCampagneBundle:Template:put'
    methods:
        - PUT
    requirements:
        template_id: \d+
starkerxp_campagne.template.delete:
    path: '/templates/{template_id}'
    defaults:
        _controller: 'StarkerxpCampagneBundle:Template:delete'
    methods:
        - DELETE
    requirements:
        template_id: \d+
starkerxp_campagne.campagne.cget:
    path: /campagnes
    defaults:
        _controller: 'StarkerxpCampagneBundle:Campagne:cget'
    methods:
        - GET
starkerxp_campagne.campagne.get:
    path: '/campagnes/{campagne_id}'
    defaults:
        _controller: 'StarkerxpCampagneBundle:Campagne:get'
    methods:
        - GET
    requirements:
        campagne_id: \d+
starkerxp_campagne.campagne.post:
    path: '/campagnes'
    defaults:
        _controller: 'StarkerxpCampagneBundle:Campagne:post'
    methods:
        - POST
starkerxp_campagne.campagne.put:
    path: '/campagnes/{campagne_id}'
    defaults:
        _controller: 'StarkerxpCampagneBundle:Campagne:put'
    methods:
        - PUT
    requirements:
        campagne_id: \d+
starkerxp_campagne.campagne.delete:
    path: '/campagnes/{campagne_id}'
    defaults:
        _controller: 'StarkerxpCampagneBundle:Campagne:delete'
    methods:
        - DELETE
    requirements:
        campagne_id: \d+
starkerxp_campagne.event.cget:
    path: '/campagnes/{campagne_id}/events'
    defaults:
        _controller: 'StarkerxpCampagneBundle:Event:cget'
    methods:
        - GET
    requirements:
        campagne_id: \d+
starkerxp_campagne.event.get:
    path: '/campagnes/{campagne_id}/events/{id}'
    defaults:
        _controller: 'StarkerxpCampagneBundle:Event:get'
    methods:
        - GET
    requirements:
        campagne_id: \d+
        id: \d+
starkerxp_campagne.event.post:
    path: '/campagnes/{campagne_id}/events'
    defaults:
        _controller: 'StarkerxpCampagneBundle:Event:post'
    methods:
        - POST
    requirements:
        campagne_id: \d+
starkerxp_campagne.event.put:
    path: '/campagnes/{campagne_id}/events/{id}'
    defaults:
        _controller: 'StarkerxpCampagneBundle:Event:put'
    methods:
        - PUT
    requirements:
        campagne_id: \d+
        id: \d+
starkerxp_campagne.event.delete:
    path: '/campagnes/{campagne_id}/events/{id}'
    defaults:
        _controller: 'StarkerxpCampagneBundle:Event:delete'
    methods:
        - DELETE
    requirements:
        campagne_id: \d+
        id: \d+
