starkerxp_campagne:
    resource: "@StarkerxpCampagneBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc
