security:
    encoders:
        Starkerxp\UtilisateurBundle\Entity\Utilisateur: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        starkerxp_utilisateur.provider:
            entity:
                class: Starkerxp\UtilisateurBundle\Entity\Utilisateur
                property: email

    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: starkerxp_utilisateur.provider
            form_login:
                check_path: /api/login_check
                require_previous_session: false
                username_parameter: identifiant
                password_parameter: motDePasse
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
