<?php

namespace Starkerxp\LeadBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * LeadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadRepository extends EntityRepository
{
    public function leadExist($origin, $externalReference)
    {
        $qb = $this->createQueryBuilder('l')
            ->andWhere('l.origin= :origin')
            ->andWhere('l.externalReference= :externalReference')
            ->setParameter('origin', $origin)
            ->setParameter('externalReference', $externalReference)
            ->getQuery();
        $result = $qb->execute();

        return !empty($result);
    }

}
