<?php

namespace Starkerxp\LeadBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * LeadActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadActionRepository extends EntityRepository
{

}
