<?php

namespace Starkerxp\CampagneBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * CibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CibleRepository extends EntityRepository
{

}
