<?php

namespace Starkerxp\CampagneBundle\Repository;

/**
 * ModuleTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleTemplateRepository extends \Doctrine\ORM\EntityRepository
{

}
