<?php

namespace Starkerxp\CampagneBundle\Repository;

/**
 * TemplateSerialisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateSerialisationRepository extends \Doctrine\ORM\EntityRepository
{

}