starkerxp_utilisateur_inscription:
    path:  /inscription
    defaults: { _controller: AppBundle:Utilisateur:inscription }
    methods: ["GET"]

starkerxp_utilisateur_mes_optins:
    path:  /mes-alertes
    defaults: { _controller: AppBundle:Utilisateur:gererMesOptins }
    methods: ["GET"]

starkerxp_utilisateur_modifier_mon_profil:
    path:  /mon-profil
    defaults: { _controller: AppBundle:Utilisateur:modifierMonProfil }
    methods: ["GET"]

starkerxp_utilisateur_supprimer_mon_compte:
    path:  /supprimer-mon-compte
    defaults: { _controller: AppBundle:Utilisateur:supprimerMonCompte }
    methods: ["DELETE"]

starkerxp_panier_ajouter:
    path:  /mon-panier/ajouter/{id}
    defaults: { _controller: AppBundle:Panier:ajouterAuPanier }
    methods: ["POST"]

starkerxp_panier_voir:
    path:  /mon-panier/details
    defaults: { _controller: AppBundle:Panier:voirMonPanier }
    methods: ["GET"]

starkerxp_panier_vider:
    path:  /mon-panier/vider
    defaults: { _controller: AppBundle:Panier:viderMonPanier }
    methods: ["DELETE"]

starkerxp_panier_retirer:
    path:  /mon-panier/retirer/{id}
    defaults: { _controller: AppBundle:Panier:retirerDuPanier }
    methods: ["DELETE"]

starkerxp_panier_valider_la_commande:
    path:  /mon-panier/valider-la-commande
    defaults: { _controller: AppBundle:Panier:passerCommande }
    methods: ["POST"]

starkerxp_panier_payer_la_commande:
    path:  /mon-panier/payer-la-commande
    defaults: { _controller: AppBundle:Panier:payerLaCommande }
    methods: ["POST"]

starkerxp_panier_paiement_echoue:
    path:  /mon-panier/paiement-echoue
    defaults: { _controller: AppBundle:Panier:paiementAEteRefuse }
    methods: ["GET"]

starkerxp_panier_paiement_valide:
    path:  /mon-panier/paiement-valide
    defaults: { _controller: AppBundle:Panier:paiementAEteValide }
    methods: ["GET"]
