services:
    starkerxp_structure.manager.entity:
        class: Starkerxp\StructureBundle\Manager\EntityManager
    starkerxp_structure.services.form_errors:
        class: Starkerxp\StructureBundle\Services\FormErrorsService
        arguments: ['@translator.default']
    starkerxp_structure.generator.entite_generator:
        class: Starkerxp\StructureBundle\Generator\EntiteGenerator
        arguments: ['@kernel']
        calls:
            - [setSkeletonDirs, ["@=service('kernel').getBundle('StarkerxpStructureBundle').getPath()~'/'~ 'Resources'~'/'~'views'~'/'~'Gabarit'"]]
    starkerxp_structure.generator.controller_generator:
        class: Starkerxp\StructureBundle\Generator\ControllerGenerator
        arguments: ['@kernel']
        calls:
            - [setSkeletonDirs, ["@=service('kernel').getBundle('StarkerxpStructureBundle').getPath()~'/'~ 'Resources'~'/'~'views'~'/'~'Gabarit'"]]
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
            - [setLocale, ['%locale%']]
    starkerxp_structure.listener.entity_subscriber:
        class: Starkerxp\StructureBundle\Listener\EntitySubscriber
        arguments:
            - "@security.token_storage"
            - "@event_dispatcher"
        tags:
            - {name: doctrine.event_subscriber, connection: default}

    starkerxp_structure.data_fixtures.uuid:
        class: Starkerxp\StructureBundle\DataFixtures\UuidProvider
        tags:
         -  { name: nelmio_alice.faker.provider }
