services:
    starkerxp_structure.manager.entity:
        class: Starkerxp\StructureBundle\Manager\EntityManager
    starkerxp_structure.services.form_errors:
        class: Starkerxp\StructureBundle\Services\FormErrorsService
        arguments: ['@translator.default']
