services:
    starkerxp_lead.manager.lead:
        class: Starkerxp\LeadBundle\Manager\LeadManager
        arguments: ['@doctrine.orm.entity_manager', Starkerxp\LeadBundle\Entity\Lead]
        tags: [{ name: starkerxp.manager.entity }]
