services:
#    starkerxp_lead.example:
#        class: Starkerxp\LeadBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    starkerxp_lead.form.lead_type:
        class: Starkerxp\LeadBundle\Form\Type\LeadType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
