services:
#    starkerxp_rabbitmq.example:
#        class: Starkerxp\RabbitmqBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    starkerxp_rabbitmq.service.rabbitmq:
        class: PhpAmqpLib\Connection\AMQPStreamConnection
        arguments: ["%rabbitmq.host%", "%rabbitmq.port%", "%rabbitmq.login%", "%rabbitmq.password%"]
        shared: false
