<?php

namespace Starkerxp\CampaignBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * CampaignCibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignCibleRepository extends EntityRepository
{

}
